import Head from 'next/head';
import Image from 'next/image';
import Avatar from '../components/Avatar';
import { CgMenuGridO } from 'react-icons/cg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/google-fav.png" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700 font-semibold">
        {/* Left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/* Icon */}
          <CgMenuGridO className="text-[30px] rounded-full hover:bg-gray-100 cursor-pointer" />

          {/* Avatar */}
          <Avatar url="/profile-pic.jpg" />
        </div>
      </header>
    </div>
  );
}
