import Head from 'next/head';
import Image from 'next/image';
import Avatar from '../components/Avatar';
import { CgMenuGridO } from 'react-icons/cg';
import { BiSearch } from 'react-icons/bi';
import { IoMdMic } from 'react-icons/io';
import Footer from '../components/Footer';
import { useRef } from 'react';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);

  const search = (e) => {
    e.preventDefault();
    var term = searchInputRef.current.value;

    if (!term) return;

    router.push(`/search?term=${term}`);
  };

  return (
    <div>
      <Head>
        <title>Bolt</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/bolt_fav.png" />
      </Head>

      <div className="">
        {/* Header */}
        <header className="flex w-full p-5 justify-end text-sm text-gray-700">
          <div className="flex space-x-4 items-center">
            <a href="https://mail.google.com" className="link">
              Gmail
            </a>
            <p className="link">Images</p>
            {/* Icon */}
            <CgMenuGridO className="h-10 w-10 rounded-full hover:bg-gray-200 cursor-pointer p-[7px]" />
            {/* Avatar */}
            <a href="https://mail.google.com">
              <Avatar url="/gmail.jpg" />
            </a>
          </div>
        </header>
        {/* Body */}
        <form className="flex flex-col items-center justify-center py-[15vh]  lg:py-[20vh] ">
          <div className="pb-[30px] flex flex-col items-center justify-center">
            <Image
              src="/Bolt_logo.png"
              width={250}
              height={85}
              alt="google-image"
            />
          </div>
          <div className="md:w-[40vw] w-[80vw] flex ring-offset-2 ring-[1.5px] hover:shadow-lg rounded-[50px] ring-gray-200">
            <BiSearch className="h-10 w-5 md:mx-3 mx-[10px]  text-gray-500" />
            <input
              ref={searchInputRef}
              type="text"
              className="focus:outline-none flex-1 rounded-[50px]"
            />
            <IoMdMic className="h-10 w-5 md:mx-3 mx-[10px] text-green-700 cursor-pointer" />
          </div>
          <div className="flex space-x-[15px] mt-[30px]">
            <button
              onClick={search}
              className="bg-gray-100 px-[20px] py-[10px] rounded-[10px] hover:ring-[1.5px] hover:ring-gray-300 "
            >
              Bolt Search
            </button>
            {/* <button
              onClick={search}
              className="bg-gray-100 px-[20px] py-[10px] rounded-[10px] hover:ring-[1.5px] hover:ring-gray-300 "
            >
              I'm Feeling Lucky
            </button> */}
          </div>
          <div className="flex space-x-[10px] text-[14px] mt-[30px]">
            <p>Bolt Search in:</p>
            <p className="text-green-700 link">Hausa</p>
            <p className="text-green-700 link">Igbo</p>
            <p className="text-green-700 link">Èdè Yorùbá</p>
            <p className="text-green-700 link hidden sm:flex">
              Nigerian Pidgin
            </p>
          </div>
        </form>

        {/* Footer */}
        <Footer />
      </div>
    </div>
  );
}

// export var refValue = term;
