import Head from 'next/head';
import React from 'react';
import Header from '../components/Header';

const search = () => {
  return (
    <div>
      <Head>
        <title>Google Search</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/google-fav.png" />
      </Head>

      
      <Header />







    </div>
  );
};

export default search;
